spring:
  application:
    name: Backend_Venue
  data:
    mongodb:
      uri: ${Mongo_URL}
      database: Venues
      auto-index-creation: true
    main:
      allow-circular-references: true
  mvc:
    favicon:
      enabled: false
  main:
    allow-circular-references: true
  spring:
    thymeleaf:
      enabled: false
