spring:
  application:
    name: Backend_Venue
  database:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}git
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    favicon:
      enabled: false
  main:
    allow-circular-references: true
  spring:
    thymeleaf:
      enabled: false
